<?php echo $this->doctype(); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('PoolTech')->setSeparator(' - ')->setAutoEscape(false) ?>

  <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

  <!-- Scripts -->
  <?php echo $this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
  ; ?>

</head>
<body>
<nav class="navbar x-navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand text-hide" id="site-header-logo" href="<?php echo $this->url('home') ?>">pHin</a>
    </div>
    <div class="navbar-actions">
      <button id="order-now-nav-button" class="btn">Preorder Now</button>
    </div>
<!--    <div class="collapse navbar-collapse">-->
<!--      <ul class="nav navbar-nav">-->
<!--        <li class="active"><a href="--><?php //echo $this->url('home') ?><!--">Preorder Now</a></li>-->
<!--      </ul>-->
<!--    </div><!--/.nav-collapse -->
  </div>
</nav>
<?php echo $this->content; ?>
<hr>
<footer>
  <p>[Footer]</p>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
