<?php
namespace Application\Exception;

use Exception;

class ProcessingException extends \RuntimeException {
  private $errorCode;


  /**
   * @param string $errorCode
   * @param string $message
   * @param int $code
   * @param Exception $previous
   */
  public function __construct($errorCode, $message = "", $code = 0, Exception $previous = null)
  {
    $this->errorCode = $errorCode;
    parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
  }


  /**
   * @return string
   */
  public function getUserMessage()
  {
    return $this->userMessage;
  }

  public function getErrorCode() {
    return $this->errorCode;
  }

}
